config/routes.rb
Challenge1::Application.routes.draw do

  resources :product_retails

  get 'search', to: "product_retails#search", as: "search"
  post 'product_retail/:product_retail_id/product_retail_offers', to: "product_retail_offers#create", as: "product_retail_offers"
  get 'product_retail/:product_retail_id/add_offer', to: "product_retail_offers#new", as: "add_product_retail_offers"
  get 'product_retail/:product_retail_id/view_offer', to: "product_retail_offers#index", as: "view_product_retail_offers"

  root "product_retails#search"

end

app/models/product_retail.rb
class ProductRetail < ActiveRecord::Base
  has_many :product_retail_offers
end

app/models/product_retail_offer.rb
class ProductRetailOffer < ActiveRecord::Base
  belongs_to :product_retail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/product_retail_offers_controller.rb
class ProductRetailOffersController < ApplicationController
  before_action :set_product_retail_offer, only: [:show, :edit, :update, :destroy]
  NOT_EXIST = "This product does not exist"
  OFFER_NOT_VALID = "This offer is not valid"

  def new
    @product_retail_offer = ProductRetailOffer.new
    @valid_offers = valid_offers
    @product_retail = ProductRetail.find_by_id(params[:product_retail_id])
    if !@product_retail
      redirect_to product_retails_path, alert: NOT_EXIST
    end
  end

  def index
    @product_retail = ProductRetail.find_by_id(params[:product_retail_id])
    if @product_retail
      @product_retail_offers = @product_retail.product_retail_offers
    else
      redirect_to product_retails_path, alert: NOT_EXIST
    end
  end
  
  def create
    @product_retail_offer = ProductRetailOffer.new(product_retail_offer_params)
    discounted_price, offer = return_price(@product_retail_offer.base_price,@product_retail_offer.offer)
    if ! discounted_price
      redirect_to add_product_retail_offers_path(params[:product_retail_id]), alert: OFFER_NOT_VALID and return
    end
    @product_retail_offer.discounted_price = discounted_price
    @product_retail_offer.offer = offer
    @product_retail_offer.save
    redirect_to view_product_retail_offers_path(params[:product_retail_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_retail_offer
      @product_retail_offer = ProductRetailOffer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_retail_offer_params
      params.require(:product_retail_offer).permit(:base_price,:product_retail_id,:offer)
    end

    def valid_offers
      valid_offers = {
        "1" => "10% off.",
        "2" => "Flat 250 off."
      }
      return valid_offers
    end

    def return_price(base_price,applied_offer)
      offers = valid_offers
      case applied_offer.to_i
      when 1
        discounted_price = (base_price.to_f - (10*base_price).to_f/100).round(2)
        return discounted_price, offers[applied_offer]
      when 2
        discounted_price = (base_price.to_f - 250.to_f).round(2)
        return discounted_price, offers[applied_offer]
      else
        nil
      end
    end
end

app/controllers/product_retails_controller.rb
class ProductRetailsController < ApplicationController
  before_action :set_product_retail, only: [:show, :edit, :update, :destroy]
  EMPTY_SEARCH = "Search box is empty."

  def index
    @product_retails = ProductRetail.all
  end

  def show
  end

  def new
    @product_retail = ProductRetail.new
  end

  def edit
  end

  def create
    @product_retail = ProductRetail.new(product_retail_params)

    respond_to do |format|
      if @product_retail.save
        format.html { redirect_to @product_retail, notice: 'Product retail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product_retail }
      else
        format.html { render action: 'new' }
        format.json { render json: @product_retail.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product_retail.update(product_retail_params)
        format.html { redirect_to @product_retail, notice: 'Product retail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product_retail.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    if params[:search].blank?
      @results = []
    else
      @results = ProductRetail.joins("LEFT JOIN product_retail_offers on product_retails.id = product_retail_offers.product_retail_id").select("product_retails.* ,product_retail_offers.offer,product_retail_offers.discounted_price").where("product_retails.product_name like ?",'%'+params[:search].to_s+'%').order("product_retail_offers.discounted_price")
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_retail
      @product_retail = ProductRetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_retail_params
      params.require(:product_retail).permit(:product_name, :retail_name, :base_price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_retail_offers_helper.rb
module ProductRetailOffersHelper
end

app/helpers/product_retails_helper.rb
module ProductRetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Challenge1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product_retail_offers/_form.html.erb
<%= form_for(@product_retail_offer) do |f| %>
  <% flash.each do |key,message| %>
    <div id="error_explanation">
    <%=message%>
    </div>
  <%end%>
  <% if @product_retail_offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_retail_offer.errors.count, "error") %> prohibited this product_retail_offer from being saved:</h2>

      <ul>
      <% @product_retail_offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :product_retail_id, :value => @product_retail.id%>
  <%= f.hidden_field :base_price, :value => @product_retail.base_price%>
  <div class="field">
    <%= f.label :offer %><br>
    <%= f.text_field :offer, :maxlength => 1 %>
  </div>
  <div class="valid_offers">
    <ul>
    <%@valid_offers.each do|key,value|%>
      <li>
        <%=key%> : <%=value%>
      </li>
    <%end%>
    </ul>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_retail_offers/edit.html.erb
<h1>Editing product_retail_offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_retail_offer %> |
<%= link_to 'Back', product_retail_offers_path %>

app/views/product_retail_offers/index.html.erb
<h1><%= @product_retail.product_name%></h1>
<h3>Base Price: Rs <%= @product_retail.base_price%></h3>

<table>
  <thead>
    <tr>
      <th>Offer</th>
      <th>Expiry</th>
    </tr>
  </thead>

  <tbody>
    <% @product_retail_offers.each do |product_retail_offer| %>
      <tr>
        <td><%= product_retail_offer.offer %></td>
        <td><%= product_retail_offer.discounted_price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'All Products', product_retails_path %>

app/views/product_retail_offers/new.html.erb
<h1><%= @product_retail.product_name%></h1>
<h3>Base Price: Rs <%= @product_retail.base_price%></h3>

<%= render 'form' %>

<%= link_to 'Back', product_retails_path %>

app/views/product_retails/_form.html.erb
<%= form_for(@product_retail) do |f| %>
  <% if @product_retail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_retail.errors.count, "error") %> prohibited this product_retail from being saved:</h2>

      <ul>
      <% @product_retail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :retail_name %><br>
    <%= f.text_field :retail_name %>
  </div>
  <div class="field">
    <%= f.label :base_price %><br>
    <%= f.text_field :base_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_retails/edit.html.erb
<h1>Editing product_retail</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_retail %> |
<%= link_to 'Back', product_retails_path %>

app/views/product_retails/index.html.erb
<h1>Listing product_retails</h1>
  <% flash.each do |key,message| %>
    <div id="error_explanation">
    <%=message%>
    </div>
  <%end%>
<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Retail name</th>
      <th>Base price</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @product_retails.each do |product_retail| %>
      <tr>
        <td><%= product_retail.product_name %></td>
        <td><%= product_retail.retail_name %></td>
        <td><%= product_retail.base_price %></td>
        <td><%= link_to 'Add offer', add_product_retail_offers_path(product_retail.id) %></td>
        <td><%= link_to 'View offer', view_product_retail_offers_path(product_retail.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product retail', new_product_retail_path %>

app/views/product_retails/new.html.erb
<h1>New product_retail</h1>

<%= render 'form' %>

<%= link_to 'Back', product_retails_path %>

app/views/product_retails/search.html.erb
<br/>
<br/>
<b><i>Create records pasting "<%=request.host.to_s+":"+request.port.to_s%>/product_retails" in the address bar.</i></b>

<div class="search_bar">
  <%= form_tag(root_url,method: "get" ) do %>
    <%= text_field_tag('search',nil, :placeholder=> "Search here.") %> 
    <%= button_tag(type: "submit") do %> Search <%end%>
  <%end%>
  <div class="out">
    <%if @results.empty? %>
      No results found <br/>
      <b>Please create records pasting "<%=request.host.to_s+":"+request.port.to_s%>/product_retails" in the address bar.</b>
    <%else%>
      <table>
        <thead>
          <tr>
            <th>Product name</th>
            <th>Retail name</th>
            <th>Base price</th>
            <th>Offer</th>
            <th>Discounted Price</th>
          </tr>
        </thead>
        <tbody>
          <%@results.each do|result|%>
              <tr>
                <td>
                  <%=result["product_name"]%>
                </td>
                <td>
                  <%=result["retail_name"]%>
                </td>
                <td>
                  Rs <%=result["base_price"]%>
                </td>
                <td>
                  <%=result["offer"]%>
                </td>
                <td>
                  <b><%if result["discounted_price"]%> Rs <%=result["discounted_price"]%> <%else%> <%end%></b>
                </td>
              </tr>
          <%end%>
       </tbody>
    <%end%>
  </table>
</div>

app/views/product_retails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product_retail.product_name %>
</p>

<p>
  <strong>Retail name:</strong>
  <%= @product_retail.retail_name %>
</p>

<p>
  <strong>Base price:</strong>
  <%= @product_retail.base_price %>
</p>

<%= link_to 'Edit', edit_product_retail_path(@product_retail) %> |
<%= link_to 'Back', product_retails_path %>